xpdAcq/xpdAn

- .coveragerc
- .flake8
- .gitignore
- .travis.yml
- run_tests.py
- setup.py
This should add the required files for Travis-CI for when we start adding code.
> ENH: add stuff for travis

- .travis.yml
- run_tests.py
- xpdan/999-load.py
- xpdan/data_reduction.py
- xpdan/glbl.py
- xpdan/tests/conftest.py
- xpdan/utils.py
- xpdan/xpdan.py
add environment variable logic to enable simulation while keep current pytest alive
in simulation, program help user to spin up local ``db`` so that he can test api and functionalities
> ENH: simulation logic

- xpdan/data_reduction.py
- xpdan/glbl.py
- xpdan/tests/test_data_reduction.py
- xpdan/tools.py
PR of putting masking and integration together.
It also address beamline staff's need on having both Q-grid and 2theta-grid chi files. 
@CJ-Wright please see if this integration make sense to you or not, thanks.
> ENH: integrate masking and azimuthal integration functionality

- README.md
> ENH: add badge

- xpdan/data_reduction.py
- xpdan/glbl.py
- xpdan/tests/conftest.py
- xpdan/tests/test_data_reduction.py
- xpdan/tests/test_tools.py
- xpdan/tools.py
- xpdan/utils.py
- xpdan/xpdan.py
> More Tests

- xpdan/data_reduction.py
- xpdan/glbl.py
- xpdan/tests/conftest.py
- xpdan/tests/test_data_reduction.py
- xpdan/tests/test_tools.py
- xpdan/tools.py
- xpdan/utils.py
- xpdan/xpdan.py
Here are the compression/decompression tools.
@chiahaoliu
> Compress mask

- xpdan/utils.py
> ENH: show seconds from timestamp in the filename

- xpdan/utils.py
Reverts xpdAcq/xpdAn#39
Wait, reverting...I don't see the seconds....
> Revert "ENH: show seconds from timestamp in the filename"

- xpdan/utils.py
fix for issue 262 under ``xpdAcq`` [https://github.com/xpdAcq/xpdAcq/issues/262]
> seconds in file name

- xpdan/data_reduction.py
fix #37 
also unify variable name. ``dark_sub_bool`` is a function argument for whether user wants dark subtraction and ``dark_sub`` is a flag for program to label whether it found a dark image.
> BUG: fix using dark_sub_bool multiple times

- xpdan/data_reduction.py
closes #65 
@sbillinge @CJ-Wright  ready for review
> Fix tif naming

- xpdan/glbl.py
@CJ-Wright This PR contains cleans after testing at XPD. It is mainly about to making xpdAn aligned with xpdAcq.
I thought most of them should've gone into master but maybe I/we just missed it.
Ready for review!
> MNT: clean after testing at XPD

- xpdan/tools.py
Please merge asap.
@sbanerjee23 @chiahaoliu
> FIX: Inclusive theshold masking

- .flake8
- .travis.yml
- xpdan/999-load.py
- xpdan/callbacks.py
- xpdan/callbacks_core.py
- xpdan/glbl.py
- xpdan/tests/conftest.py
- xpdan/tests/test_tiff_exporter.py
- xpdan/tiff_export.py
This PR includes a ``save_tiff`` in a `Callback`` version, so that it is more robust with errors which might happen during a scan.
@CJ-Wright I got stuck with ``pytest`` (limited experience), error message shows:
````IndexError: There are only 0 runs.````
in my test. Could you give me some guides/hints once you get a chance? thanks.
> tiff exporter callback

- news/setup_analysis
- xpdan/pipelines/main.py
- xpdan/tests/conftest.py
- xpdan/tests/test_main_pipeline.py
print if no background
closes #196 
Attn: @eaculb @sbanerjee23
> ENH: zero out dark/background before potentially filling them, also

- news/xpd_fixes
- xpdan/pipelines/main.py
- xpdan/pipelines/pipeline_utils.py
- xpdan/pipelines/save.py
- xpdan/startup/analysis.py
- xpdan/tests/test_main_pipeline.py
- xpdan/tests/test_main_pipeline_extra.py
- xpdan/tests/test_pipeline_utils.py
> FIX: fix a couple of issues with datums, file paths and print when

- news/fix_calibratoin
- xpdan/pipelines/main.py
> Fix calibration

- news/save_tiff_pipeline
- xpdan/pipelines/save_tiff.py
- xpdan/tests/test_a_save_tiff_pipeline.py
- xpdan/tests/test_save_tiff_pipeline.py
> add save tiff pipeline

- news/fix_dark_emit
- xpdan/pipelines/main.py
- xpdan/pipelines/save_tiff.py
So we can do tandem dark light scans
> be specific on which event streams are listened too

- news/export_callback
- xpdan/callbacks.py
- xpdan/tests/conftest.py
- xpdan/tests/test_callbacks.py
This would allow us to export our data to a drive automatically, and export our data to an external db automatically (assuming that we can work out the method of getting a connection to our db)
> WIP: write callbacks for exporting data (including to a remote db)

- news/save_server
- rever.xsh
- score.yaml
- xpdan/callbacks.py
- xpdan/formatters.py
- xpdan/startup/save_server.py
- xpdan/tests/conftest.py
- xpdan/tests/pipelines/test_main_pipeline.py
- xpdan/tests/startup/test_save_server.py
- xpdan/tests/test_callbacks.py
- xpdan/tests/test_data_reduction_core.py
- xpdan/vend/callbacks/core.py
Closes https://github.com/xpdAcq/mission-control/issues/123
closes #113
> WIP: make save server

- news/multi_detector
- xpdan/pipelines/main.py
- xpdan/tests/conftest.py
- xpdan/tests/pipelines/test_main_pipeline.py
- xpdan/tests/utils.py
closes https://github.com/xpdAcq/mission-control/issues/136
closes https://github.com/xpdAcq/mission-control/issues/152
> multi detector support

- examples/fake_xpd/replay_raw.py
- news/db_server
- xpdan/startup/analysis.py
- xpdan/startup/db_server.py
- xpdan/startup/viz_server.py
- xpdan/vend/callbacks/core.py
Closes https://github.com/xpdAcq/mission-control/issues/66
Closes https://github.com/xpdAcq/mission-control/issues/30
> WIP: get databroker server running

- news/inbound_kwarg
- xpdan/pipelines/main.py
- xpdan/startup/analysis_server.py
- xpdan/tests/pipelines/test_save_pipeline.py
Add inbound kwarg for analysis server cli
> Add inbound kwarg for analysis server cli

- examples/tomo_example.py
- score.yaml
- setup.py
- xpdan/callbacks.py
- xpdan/pipelines/main.py
- xpdan/pipelines/tomo.py
- xpdan/startup/analysis_server.py
- xpdan/startup/tomo_server.py
- xpdan/startup/viz_server.py
- xpdan/tests/pipelines/test_tomo_pipeline.py
- xpdan/tests/test_data_reduction_core.py
- xpdan/tests/test_main_callback.py
closes https://github.com/xpdAcq/mission-control/issues/161
closes https://github.com/xpdAcq/mission-control/issues/159
> WIP: build tomo server

- docs/_templates/using_servers.rst
- news/qoi_server
- setup.py
- xpdan/pipelines/qoi.py
- xpdan/startup/analysis_server.py
- xpdan/startup/qoi_server.py
- xpdan/startup/viz_server.py
- xpdan/tests/startup/test_servers.py
Closes https://github.com/xpdAcq/mission-control/issues/145
> make QOI server with amorphsivity

- docs/_templates/using_servers.rst
- docs/conf.py
- docs/xpdan.startup.rst
- news/intensity_server
- xpdan/startup/intensity_server.py
- xpdan/tests/startup/test_servers.py
> Add server for tracking intensities

- xpdan/vend/callbacks/core.py
Along with https://github.com/bluesky/databroker/pull/629 I can get xpdan (with SHED) to run against close-to-up-to-date databroker.
> FIX: be permissive about mutating documents
